### ISSUE TITLE
Python code 

### ISSUE THREAD

**Issue by shreeram3535** [tamuhey/qubogen#3]
Hi yohei,
Is there a separate python code to subtract 1 from constraints , Square them and then add them to the mini function to obtain the Q matrix.
Thanks

**Comment by tamuhey** [comment]
Are you mentioning the below equation in [the paper](https://arxiv.org/pdf/1811.11538.pdf)?

![image](https://user-images.githubusercontent.com/24998666/88073657-660d0280-cbb1-11ea-8ca3-b204eab7845d.png)

If so, the below code is that:

https://github.com/tamuhey/qubogen/blob/c11fb15f93395412187af19c44f89ecdec0706f0/qubogen/qubo.py#L102

**Comment by tamuhey** [comment]
Here is a brief explanation:

1. `np.diagflat(cost)` to obtain the diagonal matrix of `x1, x2, ...`
2. `p * np.einsum("ij,ik->jk", set_flag, set_flag)` to obtain, for example,  `(x1 + x3 + x6)^2`
3. `np.diagflat(- p * 2 * b.dot(set_flag))` to obtain, for examle, `-(2x1 + 2x3 + 2x6)`

**Comment by shreeram3535** [comment]
Thanks yohei !
